name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: NPM cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Run eslint on ./src
        run: npm run lint
